import pandas as pd
def load_and_process(path_to_csv_file):
    dataframe = pd.read_csv(path_to_csv_file)
    
    dataframe = (dataframe.drop(['id','overall_pick','team','player','position','to_year','amateur_team',
                 'points','plus_minus','penalties_minutes','goalie_games_played','goalie_wins',
                 'goalie_games_played','goalie_wins','goalie_losses','goalie_ties_overtime',
                 'save_percentage','goals_against_average','point_shares', 'games_played',
                 'goals','assists'], axis=1).reset_index(drop=True).rename(columns={"year":"Draft Year"})
                 .rename(columns={"nationality":"Nationality"}).assign(Nation_Name = lambda x: x.Nationality))
    
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('CA', 'Canada')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('US', 'USA')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('SE', 'Sweden')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('RU', 'Russia')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('FI', 'Finland')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('CZ', 'Czechia')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('SK', 'Slovakia')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('DE', 'Germany')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('CH', 'Switzerland')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('LV', 'Latvia')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('UA', 'Ukraine')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('BY', 'Belarus')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('DK', 'Denmark')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('KZ', 'Kazakhstan')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('NO', 'Norway')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('GB', 'Great Britain')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('AT', 'Austria')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('FR', 'France')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('SI', 'Slovenia')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('PL', 'Poland')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('LT', 'Lithuania')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('YU', 'Yugoslavia')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('HU', 'Hungary')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('UZ', 'Uzbekistan')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('JP', 'Japan')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('IT', 'Italy')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('BR', 'Brazil')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('BE', 'Belgium')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('BS', 'Bahamas')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('KR', 'South Korea')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('EE', 'Estonia')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('NG', 'Nigeria')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('SU', 'Soviet Union')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('JM', 'Jamacia')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('TH', 'Thailand')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('NL', 'Netherlands')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('CN', 'China')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('TZ', 'Tanzania')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('BN', 'Brunei')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('AU', 'Australia')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('ZA', 'South Africa')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('ME', 'Serbia')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('HT', 'Haiti')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('TW', 'Taiwan')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('PY', 'Paraguay')
    dataframe['Nation_Name'] = dataframe['Nation_Name'].replace('VE', 'Venezuela')

    return dataframe